### ISSUE TITLE
209A: Hitting enter on a list collect page (docket number) results in unexpected behavior (unused screen)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#100]
# Survey result on row 29

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | 1. I went to all the way to the docket number question
2. I put in some text (though numbers cause the same issue)
3. I pressed 'enter'
Expected | Either I would:
1. Go on to the next page
2. Add a new docket number field
Actual | The page blinked, but it stayed looking the same. It did remember my text. This happened several times. The progress bar does move forward.

Clicking the 'enter' button after that just did the same thing as pressing enter.

I have gone through this form before, and I went through it again after this, and clicking 'continue' does work. Pressing 'enter' on that page is what seemed to get it to misbehave.

This is me, btw. I'm just recording the bug in a way that's more comprehensive and in the current workflow.
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1DD7BTcvSdGEnixIIfbFck4NlvNus3_hZ, https://drive.google.com/open?id=1xrYFE7f0J8a74Qv8vb9yx-EBorWNA2XH, https://drive.google.com/open?id=1orT32M0_5DKIEN2YeloHCALYtki2Id-7, https://drive.google.com/open?id=14qyuFD0VgA4MdrUo3wO85dJNo9ePiui4, https://drive.google.com/open?id=1E4kWyPwcyfYe7Og3i55mNNS_nBUqlWqV
Notes | 

Error message
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
I think fixed upstream in Docassemble. But either way, refers to a screen we're not using anymore.
