### ISSUE TITLE
209A: 'other_care_custody_proceedings[i].other_parties[0]' message when select existing party. possibly obsolete

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#101]
# Survey result on row 30

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | on "Who was involved with this case?" I selected one of the pre-existing party options 
Expected | That it would go to the next screen
Actual | I got the same screen again with an error message. 
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1jIRhQZFe2jGSAzkqs_IN--lf4R3ROBUa
Notes | 

Error message
```
Error: 'other_care_custody_proceedings[i].other_parties[0]'

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
I don't think this issue is live but not enough to go on. This language doesn't appear anywhere in the 209A or any other form in the virtual court package.
