### ISSUE TITLE
209A: wrong legal standard for sex. Should be "coerce" not "pressure"

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#102]
# Survey result on row 31

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | N/A - This is a language change request not a bug
Expected | There is a fairly significant legal accuracy issue here - It lists "threatened, pressured, or forced me to have sex."  I think that "pressure" mis-states the legal standard, which requires threat, force, or duress.  I don't think "pressure" is the same as "duress" and I worry people will erroneously check this option, which is the fundamental standard for 209As.  I propose changing "pressure" to "coerce."  (I discussed this with Laura Gal and she agreed "coerce" would be acceptable.)  Happy to discuss further on slack. 
Actual | One of the options on this page is "threatened, pressured or forced me to have sex." 
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1IoIk1ra-yQZTvQDsg7H1ffX14eArkS01
Notes | 

Error message
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This was Kate

**Comment by nonprofittechy** [comment]
I think I have separately discussed this with @kateleebarry and @CaroRob . My understanding is this language exactly mirrors what MassLegalHelp says now. Can we get a clear decision?

**Comment by kateleebarry** [comment]
This should be coerce not pressure.  Pressure is not accurate.  I have discussed with Laura Gal who agrees.

**Comment by nonprofittechy** [comment]
Got it. Sounds like a good place to use the help button too.

**Comment by nonprofittechy** [comment]
Rephrased in f2f9459ec164e245d0790c40d93f69e47afae698
