### ISSUE TITLE
209A: Clarify children you are parent of / children have care/custody of

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#105]
# Survey result on row 39

**Report type:** 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion

Question | Answer
---|---
**Question** | How many children do you have under 18?
**Confusion** | I think that "Number of children you have care or custody of" is not clearly distinct from "Number of children you are the parent of."  Could we make it "Number of *additional* children you have care or custody of," or something similar.  I worry that people will think its asking how many of their own children they have custody of, as its currently written. 
**Feedback** | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
**Feedback 1** | Part of the form was confusing.
**Feedback 2** | 

---

### Test report

Question | Answer
---|---
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This was Kate

**Comment by nonprofittechy** [comment]
This has changed quite a bit.
