### ISSUE TITLE
209A: clarify which subset of children you are showing on custody page (maybe other pages too)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#106]
# Survey result on row 40

**Report type:** 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion

Question | Answer
---|---
**Question** | Which children do you need the court to give you custody of?
**Confusion** | After discussing with  Laura Gal - Laura was concerned that people might think this form is broken because they only see the children they share with defendant.  Maybe we could solve this with a subquestion that says "the Court can give you custody of children you share with the defendant," so people don't think it's broken. 
**Feedback** | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
**Feedback 1** | Part of the form was confusing.
**Feedback 2** | 

---

### Test report

Question | Answer
---|---
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This issue was from me - Kate

**Comment by CaroRob** [comment]
In 1st big language edits we added a screen that describes the orders to protect their children that a user can request from the judge: 

> Do you need the restraining order to include orders to protect your children?
> You can ask the court to:
> Give you temporary custody of the children you have in common with Alf.

I also changed the question to ask about custody of children you have in common with defendant.
