### ISSUE TITLE
209A: For defendant's physical location, apartment should be optional

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#107]
# Survey result on row 41

**Report type:** 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion

Question | Answer
---|---
**Question** | Defendant’s Physical Location
**Confusion** | Defendant's apartment is mandatory - should be optional
**Feedback** | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
**Feedback 1** | Part of the form was confusing.
**Feedback 2** | 

---

### Test report

Question | Answer
---|---
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Resolved in 3e6d936c3d5ea1bcfc32b8ececc94a5b5703322a
