### ISSUE TITLE
209A: Defendant’s Physical Location: `other_parties[0].police_violence_no` could not be found

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#108]
# Survey result on row 42

**Report type:** 

---

### Bug

Question | Answer
---|---
**Question** | Defendant’s Physical Location
**Actions** | I gave a bunch of gibberish answers.
**Expected** | proceed to next screen
**Actual** | error screen - Error
Retry

Interview has an error. There was a reference to a variable 'other_parties[0].police_violence_no' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file
**Feedback** | 

---

### Confusion

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
**Feedback 1** | I found a bug.
**Feedback 2** | 

---

### Test report

Question | Answer
---|---
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This was Kate
