### ISSUE TITLE
Survey result row 43

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#122]
# Survey result on row 43

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Test id** | Housing TRO, Case 3 - Interview row: 5
**Tester** | @Melanie Rush
**Input** | New page should open and https://www.masslegalhelp.org/housing/lt1-chapter-8-rights-decent-place-live should load
**Expected** | The page should have opened to https://www.masslegalhelp.org/housing/lt1-chapter-8-rights-decent-place-live
**Actual** | My phone went straight to the "Your landlord's action" page
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by melanie** [comment]
I believe you have the wrong @melanie in your "Tester" field! 😉

**Comment by plocket** [comment]
Sorry, melanie, we're getting our process down. Mistake on our part and we'll try to correct course.
