### ISSUE TITLE
Bad interaction with entering addresses

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#123]
# Survey result on row 44

**Report type:** I'd like to describe a test case.

More details found in #155 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Test id** | Housing TRO,Case 1 - Interview row 16
**Tester** | @John McConchie
**Input** | I typed in the user address first line. I then pressed enter to go to the next control. That created the error I describe below. 
**Expected** | the User should have been scrolled to the next text coNtrol. 
**Actual** | The screen presented the user with a multi-line ‘combo box’ drop-down list.  It is of the autocomplete type, where the user begins to type their address and identical addresses in the world/country etc. are presented to the user for selection.  This provides ‘one-stop shopping’ if the user’s correct, complete address is represented in the drop down list.  However, if it is not, then the user must proceed to fill in the balance of the text controls in the address form.  However, once the user types some text into the address field, the drop-down list then drops down and itself obscures the next few text controls, including ‘unit’ and ‘City’. When I did the test, this draping action immediately gave me an unconscious visual cue to press the “Enter” button on my iPad to clear the list from the screen and move down to the other text controls. However, doing this caused an error message and the removal of what the user had already typed in the address list.  Even if the user persevered and went back, re-entered the first line of the address, determined not to press the Enter key but scrolled down past the obstructing drop down list to the ‘City’ text control, the screen still displayed a warning under three of the first five text controls that the filling of the control was required.  At best, the user might at this point be confused.  At worst, the user might lose some confidence in the integrity of the program, given that he will be using it to correspond with the court (which might cause him to want everything to be as close to perfect as possible).
 
How did this happen?  The programmers will likely be able to fix it (if it needs fixing) in a jiffy – that is past my pay grade.  However, it may be that the text fields other than the first address line were primed to be fed with data from the address text field (most people’s addresses would likely be represented in the drop-down list) and when no data was forthcoming, this somehow triggered the message that the control must be filled out.
 
It would not be a fatal error at all for a persistent and confident user but an insecure user might be somewhat ‘thrown off’ by the events unleashed by use of the Enter key.
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Good point, this is something I noticed in the past that needs to be fixed upstream. We can try opening a related issue at jhpyle/docassemble

**Comment by plocket** [comment]
More details found in #155

**Comment by nonprofittechy** [comment]
Fairly certain Jonathan is working on this issue now, but it's one we can't fix on our own. It's on his radar.
