### ISSUE TITLE
Housing TRO: wrong court returned given the address provided

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#124]
# Survey result on row 45

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Test id** | Housing TRO Case 3- Sign row: 2
**Tester** | @MelanieRush
**Input** | Court_county and court_name
**Expected** | Worcester County and Central Housing Court- Dudley Session
**Actual** | I got Hampden County and Western Housing Court -Springfield Session
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Melanie--can you share the address you tested with?

**Comment by plocket** [comment]
Test checklist was incorrect 👍
