### ISSUE TITLE
Housing TRO: open explanation of conditions in new window when click continue

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#125]
# Survey result on row 46

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Test id** | Housing TRO, Case 2 - Interview row: 5
**Tester** | Robyn Casper
**Input** | Clicked Continue from the screen “Housing temporary restraining order”
**Expected** | New page should open and https://www.masslegalhelp.org/housing/lt1-chapter-8-rights-decent-place-live should load
**Actual** | The screen “your landlord’s actions” loaded instead
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
![image](https://user-images.githubusercontent.com/7645641/81206126-a3da9180-8f99-11ea-8d15-90d2f87c46b5.png)

I don't know if we can clarify this screen, but when you click Continue it is not supposed to open up a new window with the link. Only if you click the link (highlighted in image above)

Robyn: if you can comment on how to make this easier to follow on this screen, we should adjust language to match.

**Comment by plocket** [comment]
I think the confusion may have been between rows in the testing checklist as opposed to something on the page. A link that says 'here', though is something to flag for edit after the MVP. It's not good for screen readers.

I would suggest:

You can [read more about your rights here](the link).

Also, there's a typo - the 'can' is currently missing.
