### ISSUE TITLE
209A: Slides out of order - Affidavit of Care intro slides intermingled with Relief slides 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#127]
# Survey result on row 53

**Report type:** I'd like to tell you something else.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:
The "What Are You Asking For?" slide is appearing in a weird place, after the initial Affidavit of Care slides.  - Kate 

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
Now that I think about it, I think it's actually stray affidavit of care intro slides that are appearing among the relief questions, not relief questions appearing in the affidavit of care slides, if that makes sense.

**Comment by nonprofittechy** [comment]
I haven't been able to reproduce this so I'm thinking it's something we already fixed. Please reopen if you can trigger this behavior again
