### ISSUE TITLE
209A - Make sure on package, we don't allow juvenile court. Need to comment out code in Aff. of Care and Custody unless a standalone form

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#129]
# Survey result on row 49

**Report type:** I'd like to tell you something else.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:
This is Kate: What court is your case being heard in? Slide - Lists juvenile court as an option.  Juvenile court is not an option for 209As.

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
nevermind this comment, I realized the juvenile court reference is probably related to the affidavit of care specifically

**Comment by nonprofittechy** [comment]
I think we still need to fix this for purposes of this package. I'll make a note to go in and change this soon.
