### ISSUE TITLE
209A: "This is what will go into your Affidavit:" add language making clear that people can edit 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#130]
# Survey result on row 50

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | This is what will go into your Affidavit:
**Confusion** | It might not be clear to people to that they can edit.  
**Feedback** | Maybe add "Is there anything you want to add or change" or something like that.  This is Kate, based on feedback from Laura. 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
New language in f2f9459ec164e245d0790c40d93f69e47afae698
