### ISSUE TITLE
209A: change "need" to "want" in relief questions? 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#131]
# Survey result on row 51

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | What are you asking for?
**Confusion** | need v. want
**Feedback** | Instead of asking people what they "need," should we say "want"? Kate, based on Laura feedback. 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
@CaroRob, I think this was a deliberate choice we made on pair programming, right? I'll defer to the family law experts

**Comment by CaroRob** [comment]
Yes, this language comes from Jeff Wolf - it's one of our principles at MassLegalHelp to always use the verb need when we talk about people asking the court for court orders.

**Comment by nonprofittechy** [comment]
Based on our standup call 5/12/20 it sounds like this is OK to keep as "need"
