### ISSUE TITLE
209A: Bug in Defendant confidential information form 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#135]
I was on the "Information for Service" in the defendant confidential information form.  I answered all the questions on the field "no."  I pressed continue. I got the attached error. 

[209A.Affidavit.Error.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4588698/209A.Affidavit.Error.pdf)

**Comment by nonprofittechy** [comment]
@kateleebarry make sure you're running the 209a_package.yml file, not the affidavit one. Looks like this screenshot shows you running affidavit. Maybe it was just open in a different tab and you switched to it by mistake?

**Comment by kateleebarry** [comment]
I just tried to replicate it using the correct interview and I got this error "Interview 209A-review.yml"this time at the same point.

**Comment by kateleebarry** [comment]
Interview 209A-review.yml not found

**Comment by kateleebarry** [comment]
I am using this: https://apps-test.suffolklitlab.org/interview?i=docassemble.MAVirtualCourt%3Adata%2Fquestions%2F209a_package.yml&reset=1

**Comment by kateleebarry** [comment]
never mind, now nothing works for me
