### ISSUE TITLE
209A: Field that doesn't belong on "Should defendant have to pay you money"

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#136]
# Survey result on row 58

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Should [defendant] have to pay you money?
**Confusion** | Includes the "the court should order relief related to my minor children" option - doesn't belong on this page 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
I think this box should ALWAYS be checked if there are minor kids. Agreed? I propose removing the question

![image](https://user-images.githubusercontent.com/7645641/81313851-6556dc80-9056-11ea-9893-ed5f537d077c.png)

**Comment by nonprofittechy** [comment]
Will implement above idea for now. Can reopen if that's wrong solution.
