### ISSUE TITLE
209A: Duplicate

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#137]
# Survey result on row 59

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | How many children do you have under 18?
**Confusion** | Erroneous screen - I previously told the interview that I don't have children. 
**Feedback** | This is Kate. 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
I made a more detailed issue directly on github on this issue

**Comment by nonprofittechy** [comment]
Closed - duplicate
