### ISSUE TITLE
209A: Make field optional re what floor is defendant's address on 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#139]
# Survey result on row 60

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | [Defendant's] Physical Location
**Confusion** | The field "What floor is “address” on?" is mandatory.  I'm not sure how this would work for multi-floor standalone houses.  Maybe make optional?
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | 
**Tester** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This is Kate btw

**Comment by nonprofittechy** [comment]
Resolved in 7a00368
