### ISSUE TITLE
209A: Bug on "Information about [defendant's] car" screen when selecting "no car"

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#141]
I tried to say that the defendant didn't have a car, but it wouldn't let me proceed without selecting values for color and year, even though these fields were grayed out. 
See picture. 
<img width="517" alt="no car bug" src="https://user-images.githubusercontent.com/63356951/81223584-3556fd00-8fb4-11ea-8f28-0e07166329a6.png">

**Comment by nonprofittechy** [comment]
Resolved in .53
