### ISSUE TITLE
209A:There was a reference to a variable 'users[0].previous_addresses[0].on_on_line' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#142]
Went through interview, signed forms, got this error: 

[There was a reference to a variable 'users[0].previous_addresses[0].on_on_line' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file..pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4589301/There.was.a.reference.to.a.variable.users.0.previous_addresses.0.on_on_line.that.could.not.be.looked.up.in.the.question.file.for.language.en.or.in.any.of.the.files.incorporated.by.reference.into.the.question.file.pdf)

**Comment by nonprofittechy** [comment]
Typo in virtual_court_support.py, fixed in .53 / c8fb899
