### ISSUE TITLE
TRO: question order - court requested before contact information

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#146]
# Survey result on row 47

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet**: | 
**Test id** | Housing TRO, Case 4 - Interview row:14
**Tester** | @emmacoreno
**Input** | Click continue
**Expected** | Screen “what is your contact information” should load
**Actual** | The interview went directly to the “what court is your case being heard in”, skipping the contact information question
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
This is because the old court question required address--it doesn't anymore. We may go back to this question order once we feel confident about the new court selection screen that also handles district court.
