### ISSUE TITLE
All: Missing 'back' button on signing documents

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#148]
On the “sign your documents” page you can’t back up (no back or cancel button)

**Comment by nonprofittechy** [comment]
On a phone in vertical mode, the back button is hidden to allow more room for signature field. In landscape mode, the back button is there. Also you can use browser back button. This is upstream behavior--not sure if we should ask for fix or what.

**Comment by plocket** [comment]
I think we should. There's an expectation that the back button will be there and then it's not. It was very confusing to _me_ and I have a fair amount of technological literacy. Others have been confused as well. Also, from what I understand, the form behaves better when the DA back button is used, so we want people to use it.

Also, it takes up vertical space, not horizontal space. Maybe I'm wrong about this, but it seems like what you need in a signature is horizontal space, so I'm not sure why the situation isn't reversed regarding portrait vs. landscape modes.

**Comment by nonprofittechy** [comment]
@plocket can you open an issue upstream? This is not something we can fix.

**Comment by plocket** [comment]
Done at https://github.com/jhpyle/docassemble/issues/300

**Comment by plocket** [comment]
Apparently, the back button does appear for a signature page on not-our-repo: https://github.com/jhpyle/docassemble/issues/300#issuecomment-642000509.

**Comment by plocket** [comment]
Is our problem just on the mobile version?

**Comment by plocket** [comment]
Sorry, I'm looking aback at our question and I think the mobile thing is the specific problem we're talking about.

**Comment by plocket** [comment]
This was the reply to that: https://github.com/jhpyle/docassemble/issues/300#issuecomment-642584438. From what I remember, we _are_ using the config for a back button, but still getting a 'clear' button. I'm a little too wiped to figure that out right now. Wish I could set a reminder for this.

**Comment by plocket** [comment]
Do you remember which file that config would be in, @nonprofittechy ?

**Comment by CaroRob** [comment]
I just checked on my old iphone se, in vertical mode,  there is a back link, in blue top left in black bar at the top. And it's pretty clear that you can go back.
Although - different issue - when I go to review screen, screen is too big to see everything and I am unable to scroll down.
