### ISSUE TITLE
TRO - User allowed to continue without selecting an option for relief

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#149]
At the question "What are you asking the court to do? (page 5)," user should not be able to proceed to page 6 without checking one of the three options ("Let me back into the apartment," "Provide me utilities," or "Stop breaching my quiet enjoyment)." However, clicking "Continue" with all three boxes **unselected** nevertheless allows user to proceed to next question. 

Link to question on reflief: https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12TROtesting%3AHousing_Temporary_Restraining_Order.yml&session=S6PzDTwxLxFjnAd3dDCvst2IjGcuEL1X

Link to following question, which should not appear: https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12TROtesting%3AHousing_Temporary_Restraining_Order.yml&session=S6PzDTwxLxFjnAd3dDCvst2IjGcuEL1X

**Comment by nonprofittechy** [comment]
Good catch--I think we can do this post release, but we can add some validation code on this screen.

**Comment by nonprofittechy** [comment]
Since I'm already editing this file, I went ahead and added validation on this page.
