### ISSUE TITLE
Get user feedback on final screen language

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#153]
Specifically, 'Great job!'

So far, the people that I've asked have found it uncomfortable.

**Comment by nonprofittechy** [comment]
This is the generic LawHelpInteractive final interview screen:

![image](https://user-images.githubusercontent.com/7645641/81412639-26865c80-9112-11ea-93d5-de51c58d3e45.png)

**Comment by nonprofittechy** [comment]
Progress screen in MADE
![image](https://user-images.githubusercontent.com/7645641/81412877-85e46c80-9112-11ea-9e86-ad392610ab26.png)

**Comment by nonprofittechy** [comment]
Final download screen in MADE

![image](https://user-images.githubusercontent.com/7645641/81412981-aca2a300-9112-11ea-8ef0-bb81f035a89e.png)

**Comment by plocket** [comment]
'Congratulations' does look a bit better, but if we're waiting to change it till we have user testing, we can test it out then.

**Comment by plocket** [comment]
From Slack:
> Could be another good place to solicit feedback from Transcend. they had some useful thoughts on the language for plaintiff/defendant that we should look at when have a form that needs that question.

**Comment by nonprofittechy** [comment]
Well we took out this language, so closing for now.
