### ISSUE TITLE
209A confusing question and typo

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#156]
# Survey result on row 65

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Keeping information private (impoundment)
**Confusion** | "keeep" is spelled wrong; I don't think it should ask "why" on this page, just what information should be impounded.  The next question asks why, and it doesn't really make sense with the form to ask why here. 
**Feedback** | This is Kate 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Resolved in 7188ed3
