### ISSUE TITLE
I'd like to describe a test case., survey row 69

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#166]
# Survey result on row 69

**Report type:** I'd like to describe a test case.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1BBI4PLLA-glSDa2O0dgO4knw5Alm4lC9DeL-iyan4A8/edit#gid=0
**Test id** | 209A Child Support, Case 01 - Interview row: 5
**Tester** | Michelle (she/her)
**Question** | Signing Under Oath
**Input** | See screen for taking oath of no perjury
**Expected** | 
**Actual** | Typo reported: There is a typo on this page. Next to the checkbox, the word 'purjury' should be spelled 'perjury'.
**Link** | 
**Pic** | 
**Notes** | Thanks for being such good sports!

**Error message**
```
https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground12sitchup%3A209A-just-child-support.yml&session=Lwg07jm5Sf1j78lIVoTJ66CEjCkfY8T4
```

---

### Thank you!

**Comment by nonprofittechy** [comment]
This is fixed a few commits ago (I think by Sunday at least). @plocket what is your process for pointing testers at the latest commit?

**Comment by plocket** [comment]
To follow up, oh so much longer, the process is to have a Project in my Playground that I sync up with this repo's `master` on a regular basis. Till recently, I was thinking this would be useful as it would allow me to switch to a different branch depending on what we want to test. I'm not sure that's true, though, as it really doesn't give fine-grained control and I've been considering doing that only for specific occasions with special instructions.

Do we want something that will be updated more automatically? If so, give me the link and I'll update where testers are going.
