### ISSUE TITLE
209A: Review screen about children confusing

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#174]
**Summary:**
The Children review screen said I didn't have any children even though I said I did (they just weren't minor). I, presumably, went to that screen looking for help with children 18 or older.

**What I did:**

On 'Who do you need this order to protect?' I answered 'Myself and my children'. Later, I answered that I didn't have any children under 18. 

**What I expected:**

I expected the Children review screen to say, 'You told us that you do not have children under 18.'

**What actually happened:**

In the Children review screen it said, 'You told us that you do not have children.'

I was confused, because I did say that I had children.

**Comment by nonprofittechy** [comment]
There's no reason to systematically make issues like this yet. That is all pretty rough draft code. (for review screens, that is). Feel free to open if you run into them naturally, but the code is not ready to be tested.
