### ISSUE TITLE
209A: add validation on court selection screen to prevent filing in Superior Court if dating relationship

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#176]
See https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/171/files

changes in Page 1. The validation code is on the wrong question

**Comment by kateleebarry** [comment]
I would say that superior  court should only be prevented if dating/engagement is the *only* relationship - I don't want to rule out people who plead dating along with another grounds, like maybe dating + have a child together

**Comment by CaroRob** [comment]
I'm with Kate on this one too. We can describe reasons why someone might choose superior court over district/bmc or probate and family, but we should not have the technology make the decision for them. If the plaintiff defendant relationship is **only** dating or dated, plaintiff cannot file in superior court, if they have anything more than that relationship they may file in any of their local courts or the courts where the abuse happened.

**Comment by nonprofittechy** [comment]
Got it--this was mostly a note so I remember to move the existing logic to the right question.

**Comment by kateleebarry** [comment]
@nonprofittechy do you know if this has been dealt with? This is maybe MVP.

**Comment by nonprofittechy** [comment]
Fixed in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/463
