### ISSUE TITLE
Unable to use text to speech feature on iPhone 11 (not clear if transitory or bug)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#178]
# Survey result on row 70

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Question** | Each page of the Housing TRO
**Actions** | Filling out the form on my iPhone11, I clicked the play button on the audio box feature at the top
**Expected** | I thought the text on the page would be read aloud
**Actual** | When filling out the form on my iPhone11, clicking the play button at the top of each page resulted in the word "Error" appearing in the audio box with no audio coming out.
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
This seems likely to be a transitory error with the voice rss service, but I don't have an iPhone to test with. I'm assuming this is Safari, but iOS version would be nice
