### ISSUE TITLE
209A Impoundment: Questions on need for impoundment (Page 3 and 4)

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#180]
The questions on keeping information private (Pages 3 and 4) are confusing. Page 3 asks if there is "any information on this form that you need to keep private?" In my test, I selected "no." The next question, Page 4, then asks "Why do you need to keep this information private?" and the answer is required to continue the interview. 

It would appear that Page 4 is really asking "why are you filing a motion for impoundment?" and not asking for an explanation of the 'yes' or 'no' response to the previous question, but that isn't clear.

**Comment by nonprofittechy** [comment]
Resolved in .70
