### ISSUE TITLE
209A Impoundment: Placeholder download screen for signed PDF 

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#181]
Language on the placeholder download screen for the signed 209A Motion for Impoundment & Affidavit (Page 11) is incomplete. Instead of providing actual instructions for downloading the PDF, it reads: 

> **Next steps**
> 1. Step 1
> 2. Step 2

**Comment by nonprofittechy** [comment]
@plocket @maevemacglinchey we should revise the test instructions to clarify that the placeholder download screen won't be used for the real interview.
