### ISSUE TITLE
209A Impoundment: Letter spacing is off in the PDFs 

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#183]
Spacing is off in the description of the document on both the draft and signed PDFs for the Motion for Impoundment & Affidavit (see attached example):
[Draft Motion_for_Impoundment - 5-13-20 - R.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4626377/Draft.Motion_for_Impoundment.-.5-13-20.-.R.pdf)

**Comment by nonprofittechy** [comment]
Any PDF wizards able to look at this one? Possibly @maevemacglinchey ? I'm suspecting an issue with a font not being fully embedded in the PDF, but I'm not sure.

**Comment by nonprofittechy** [comment]
I haven't seen this issue again. Suspect it was a one-off fluke but we can revisit it if it comes up again
