### ISSUE TITLE
How do we best identify text that has an informational pop out

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#185]
Currently, the text that has more information/an explanation is in green.
![image](https://user-images.githubusercontent.com/49881041/81963472-6b7c2880-9615-11ea-80e1-f27a443abe84.png)

We should determine a better way to indicate to the user that this is something that they should tap on to get more information, such as a question mark icon as suggested by @plocket.

(Flagged in stand up on 14 May 2020.)

**Comment by plocket** [comment]
What's the issue number of the duplicate, @nonprofittechy ?
