### ISSUE TITLE
209A Affidavit: Confusing punctuation in default affidavit text 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#194]
# Survey result on row 72

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Describe the incident
**Confusion** | The default text that shows up on the screen to a user includes quote marks and a colon.  
**Feedback** | Kate Barry

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
<img width="802" alt="describe the incident" src="https://user-images.githubusercontent.com/63356951/81984960-92316380-9603-11ea-8f38-8f74181dcdcb.png">

**Comment by nonprofittechy** [comment]
Resolved in .70
