### ISSUE TITLE
How to ask the user about how the court should contact them

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#195]
What is the best way to ask the user for contact information? 

The contact question currently looks like this:
![image](https://user-images.githubusercontent.com/49881041/81983904-5c58a300-9634-11ea-9445-a47b2a33fddb.png)

When you click the contact pop out, the message is:

![image](https://user-images.githubusercontent.com/49881041/81984017-814d1600-9634-11ea-8831-ae20108ce55d.png)

**Comment by CaroRob** [comment]
We have contact notes in there now - leaving there for MVP I think and then revisit if when we get user feedback?
