### ISSUE TITLE
Requirement of last names for Plaintiff and Defendant

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#198]
Currently in 209A there is an inconsistency for the requirement of a last name. Plaintiff's last name is required while Defendant's last name is not. 

We should revisit this in Phase 2.

**Note**: This is a big picture issue and not limited to 209A.

**Comment by nonprofittechy** [comment]
From just about consensus on our standup meeting, we should make it required to reduce errors. If someone doesn't have a last name, they can enter something else here to make that clear.
