### ISSUE TITLE
209A Affidavit: Text doesn't flow 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#203]
eel like using the affidavit interview as is creates something that is a little strange when put into the final affidavit form.  The text that is created doesn't really flow with the pre-set part of the form.  Maybe the part that says "the following is a brief summary..." could go at the end and be a "the above is a brief summary..."  Even with that, it still reads weird with the dates being listed twice, and doesn't really flow as a complete sentence.
![image](https://user-images.githubusercontent.com/63356951/82092824-f6b5f680-96c7-11ea-8cef-f1e297a66e8c.png)

**Comment by kateleebarry** [comment]
@nonprofittechy

**Comment by CaroRob** [comment]
@kateleebarry we made some changes, moved the summary sentence to the end, still get double dates at the top,  we could play with this a little more so for the most recent incident, people would write in a different order. The pre-set affidavit, on or about date, the defendant.... omits the ability to insert location naturally, We could use the court forms,  **On or about** _date our user supplies in whatever form_, **Defendant ...** we supply "committed the most recent abuse. At _time of day supplied by user_, We were _location supplied by our user_ " 
Then let our users carry on from there. Then for subsequent incidents we continue with what we are doing now.
Or we just ignore the court supplied prompts in the relaying of the affidavit.. Enter Date and allow user to repeat and write their own statement?
