### ISSUE TITLE
Note to user re: delay in email

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#205]
Email arrived but it took over 10 minutes. So maybe there should be a disclaimer not to worry if the email doesn't arrive right away.

Suggestion made by Emma Coreno in [TRO test case 04](https://docs.google.com/spreadsheets/d/1eacnmxENHi0EU_srPopokA-GEHL5z2taLwn2945Hj5Q/edit#gid=0) at Housing TRO, Case 4 - Interview row: 47.

**Comment by nonprofittechy** [comment]
Resolved in current master branch
