### ISSUE TITLE
209A: Visitation screens need to be finished!

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#218]
# Survey result on row 76

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Before you ask the judge to order visitation
**Confusion** | These screens are not finished and loop back and forth to each other 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
This is Kate.  My report was really vague, but I wanted to just make a note that the visitation screens are not finished, so they don't get forgotten.

**Comment by nonprofittechy** [comment]
Resolved in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/280 -- still needs additional SME language review as I shortened it quite a bit. It's also still rather long
