### ISSUE TITLE
209A Child Support Affidavit: Language on wrong slide

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#219]
The subquestion language on this question doesn't really belong on this screen.  It's covered by the following screen.  I would move this language to the next question. 

![image](https://user-images.githubusercontent.com/63356951/82255792-3f1d2080-9923-11ea-9a89-0866b21ce641.png)

**Comment by nonprofittechy** [comment]
No longer used in f2f9459ec164e245d0790c40d93f69e47afae698
