### ISSUE TITLE
209A Complaint Page 1: Prior/pending actions not populating on form

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#222]
I said "no" about there being prior or pending actions against the defendant and the box was not checked on the form. 
![image](https://user-images.githubusercontent.com/63356951/82257054-5fe67580-9925-11ea-9da1-4496e447890e.png)

**Comment by CaroRob** [comment]
Just asked Jodi to test on [Slack](https://a2jtech.slack.com/archives/C01245TSZNJ/p1592574055469700?thread_ts=1592492643.460700&cid=C01245TSZNJ)

**Comment by nonprofittechy** [comment]
I don't see this error in the current branch.
