### ISSUE TITLE
209A Affidavit of Care: "Law Guardian" language is confusing

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#226]
The affidavit calls GALs "law guardians."  I've never heard anyone use this term in Massachusetts (or anywhere else for that matter, but I don't practice anywhere else).  I think we need to remove this term as it is confusing.

**Comment by nonprofittechy** [comment]
This could be a mostly New York State term. If people don't use it here, we should take it off.

**Comment by kateleebarry** [comment]
It's not a Mass term - I agree - take it off
