### ISSUE TITLE
209A: Paternity question

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#229]
I feel that we always need to ask as its own question whether there are any current or prior actions for paternity.  

Reasoning copied from Slack: 

 I'm concerned about a couple issues relating to the question on Complaint Page 2 about whether there have been actions for "paternity" between the parties.  Right now it seems like questions is answered solely based on whether someone picks "paternity" as their case type on the affidavit of care? If that's correct, I think this approach has a few issues.  First, there might have been a prior or pending action for paternity that doesn't come up on the affidavit of care.  E.g., cases where one party was adjudicated to be NOT the father, would still be prior paternity actions, but would not be included on the affidavit of care, because the child would not be a child of both the parties.  Also, a mother may file to establish paternity while still pregnant, so there would not be any children yet to trigger the affidavit of care. So I think we always need to separately ask whether there are any additional prior or pending actions for paternity between the parties, regardless of their answers on the affidavit of care.

**Comment by nonprofittechy** [comment]
I think we have partially resolved this, but leaving open because we need to update the logic to reflect the reworked question
