### ISSUE TITLE
TRO: "File not found" when I open the Preview PDF

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#231]
# TRO Preview PDF Bug (Survey result row 78)

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Question** | Nearly finished (TRO)
**Actions** | Clicked on the preview pdf
**Expected** | PDF would open in a new tab
**Actual** | New tab opened and the message was 'File not found'
**Feedback** | The link of the error page: https://apps-dev.suffolklitlab.org/uploadedfile/3100/file.pdf

**Comment by nonprofittechy** [comment]
This usually means that the file was opened in a different browser session/not logged in. Do you have any more info about how this was opened? If it's _not_ tied to that want to figure out how to prevent it happening again.

**Comment by plocket** [comment]
Possible specific source identified in DA Slack by Jonathan:
> ...if a user has a tab open in an interview and then opens the same interview in a separate tab, using a link containing reset=1, and then they go back to their original tab, clicking on a link to a file in that tab will lead to a "file not found" error.

We _are_ using `reset=1` so that each test gets us a fresh interview, but there's no way to at this point if this is what was happening on these occasions. We're going to try to keep an eye out for this in the qa testing team in the future. If this happens outside of the context of multiple tabs with `reset=1`, we'll get in touch.

Followup question:  It is the behavior we want, so we may have to deal with the complications, but is there a url argument that will start a new interview instead of resetting the current one?

**Comment by plocket** [comment]
Got my answer in Slack:
> &new_session=1

**Comment by nonprofittechy** [comment]
If this is just an artifact of our testing links, hopefully we won't run into this again. Given unpredictable nature, let's try changing the link we distribute and only reopen if this comes back.
