### ISSUE TITLE
209A: thoughts on rearranging Aff. of care and custody

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#236]
~1. Combine the two intro screens for aff. of care and custody~
~2. Move the address questions about kids to the end of the interview~
~3. Can we make the court field on the other care/custody cases an AJAX input. Does it allow you to type something that doesn't match? We think so. Alternative is to have a drop-down for geographic area.~
~1. Change "how were you involved" to "what was your role?" Change to radio buttons.~
1. Change the status options. Caroline and Kate to figure out what these options are.
~1. Move the "are there any other people in the case" onto the main case information screen. Make it a checkboxes field: who else was in this case? "DCF, The abuser, someone else"~
1.

**Comment by kateleebarry** [comment]
Also from the call itself - we discussed moving the affidavit of care further to the end of the interview, so if people are tired, this is the interview that they are giving imperfect answers on.
