### ISSUE TITLE
209A: Cultural Competency

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#241]
Solicit feedback from culturally targeted DV groups to make sure that interview packet is inclusive and appropriate to users from various cultures.

Suggested groups included:
- ATASK (Asian) 
- AFAB (Haitian)
- Saheli (South Asian)
- MAPS (Portuguese speakers)
- The Network/La Red (LGBTQ)
- Fenway Health (LGBTQ)
- Urban League (African-American)
- Amal Women's Shelter (Muslim)

**Comment by nonprofittechy** [comment]
I think we've started this discussion. May want to revisit to check our progress but I don't think we need to leave it open for now.
