### ISSUE TITLE
TRO: '(cell) (other)' text on PDF, row 80

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#249]
# Survey result on row 80

**Report type:** I'd like to describe a test case. (internal use only)

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1OF-NQFy7aRNmh4AZkTp-Td9xO9Y2gtHOeQm5iUxDLJA/edit#gid=0
**Test id** | Housing TRO, Case 04, Run 01 - Interview row: 66
**Tester** | Melanie Rush
**Question** | Nearly Finished
**Input** | Prior to the PDF preview page no telephone number had been input for tenant
**Expected** | telephone number for tenant on page two of form should have been blank
**Actual** | (cell) (other) appeared on the preview PDF on the tenant telephone line
**Link** | 
**Pic** | https://drive.google.com/open?id=1ENxJHxihXr3LgRq8kYze82vydwyHQhxr, https://drive.google.com/open?id=19k2dlT1XuZGWq-UG_109P5DvU-1wPSSl, https://drive.google.com/open?id=1l4MLGeJzqqur0v8xpPX9q8C2IAHHyOli
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by plocket** [comment]
Duplicate of #79 with a bit more detail.

**Comment by nonprofittechy** [comment]
Resolved in bbe6e9b43b72b2d3e199ba094727eac185e60dd4
