### ISSUE TITLE
209A: Placeholder text still Pg. 2 content, row 81

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#250]
# Survey result on row 81

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Question** | Before you ask the judge to order Visitation
**Actions** | no answer it was an informational page
**Expected** | The title makes it appear there will be a description here about things to consider before asking for visitation
**Actual** | "The doc that was linked in the pg. 2 doc" is the text on the page, which links to a google doc 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Resolved https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/280
