### ISSUE TITLE
209A: Details about service should be earlier in the interview, row 83

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#252]
# Survey result on row 83

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | The title/lead in on Defendant information
**Confusion** | I think this part about service and describing that process should be put more towards the front of the entire interview. I think it is important that people know before they get 20-30+ minutes into a form how service is going to happen; that it will be by the police; that it may not be immediate; that they aren't protected until the order is served I think deserved a highlight at the forefront....by this point in the form applicants are going to be tired and might not read all of these informational slides and instead just click through to where they need to fill in answers
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
I think we can consider having a video that goes into background about the 209A. But I'm going to put this into the "wontfix" category for now. Revisit with user feedback.

**Comment by nonprofittechy** [comment]
@CaroRob flagging this for you in case you disagree
