### ISSUE TITLE
209A Defendant Information Form: Answer doesn't fit into field

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#266]
Not sure if this was already flagged for an addenda but there isn't really enough space here for all the options (which probably isn't terribly uncommon for all to be checked if a person owns a legal gun)

![image](https://user-images.githubusercontent.com/63356951/82478851-85978a00-9a9f-11ea-8f33-60933920bc0d.png)

**Comment by kateleebarry** [comment]
Could shorten "firearms ID" to "FID" in the output, get rid of the "and" and it might all fit

**Comment by nonprofittechy** [comment]
Adjusted size to 8 pt for this field. Also change "a gun" to "gun"
