### ISSUE TITLE
209A Defendant Information form: Issue with fields

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#270]
When I was trying to create sample outcome PDFs for testing, I noticed that some of the fields (date of birth, phone numbers) were restrictive in terms of what kind of data I could input, in a way that was preventing me from creating some expected outcomes. I don't think this is effecting anyone using the interview, just me trying to create sample PDFs. I used a PDF editor to change the date of birth and @plocket 
[Blank.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4659018/Blank.pdf)

**Comment by nonprofittechy** [comment]
Can you give an example Kate? Do you think we should change this for users?

**Comment by kateleebarry** [comment]
It was the first DOB field in particular - It was not letting me put in things like "30" on the DOB field.  It doesn't need to be changed for the user and it isn't that important, but it was something I was discussing with @plocket on Slack and she suggested that I fix the fields on the PDF, so  I did that.  This is not super important though.
