### ISSUE TITLE
Interview generator: Unit is not included when you use address.on_one_line()

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#274]
# Survey result on row 86

**Report type:** A test case (qa)

**Contact info**: Reach out to me, Chandler Burnham

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1GMnCNFl0rPKX2U25dN2KfRkkP9tZ5C6rtvsX3gqCQCc/edit#gid=1780719876
**Test id** | Housing TRO, Case 1, Run 02 - Preview row: 10, Housing TRO, Case 1, Run 02 - Preview row: 13, Housing TRO, Case 1, Run 02 - Preview row: 26
**Tester** | Chandler Burnham
**Question** | Not really a page but the PDF itself, both the preview and signed versions
**Input** | The important actions include entering unit numbers for both the user and the other party's address. See spreadsheet for more info.
**Expected** | 4 Lee st, Unit 2, Fez, MA 00000 & 2 Howe Rd, Unit 3, Fex, MA 00000
**Actual** | Each address field, both for user and other party, did not include the unit number entered e.g. 4 Lee st, Fez, MA 00000
**Link** | 
**Pic** | https://drive.google.com/open?id=1z0NXs4DwNRpR5NFeh-nPo7n1sPfvLG7J
**Notes** | 

**Error message**
```
N/A
```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Thanks Chandler, we need to change this in the interview generator. I don't know why this is the default

**Comment by nonprofittechy** [comment]
I've addressed this in all of of the 209A and TRO forms. Still need to do in the interview generator
