### ISSUE TITLE
209A: child support affidavit

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#286]
Expenses related to your children

We can reflect names of children here, rather than current language: "Do you pay for childcare for the children that you share with the defendant?"

**Comment by CaroRob** [comment]
If they have more than a couple of children, it makes the question in the field very long, I will put the variable in the subquestion or question, in languagefixesMilestone1 PR but leave the children in the field question.

**Comment by nonprofittechy** [comment]
I agree, that makes sense.
