### ISSUE TITLE
209A: Photo question repeats after signature

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#301]
# What I did
1. Answered "Can you provide a photo?" with "No"
1. Proceeded to signature box
1. Signed box
1. Continued to the next page

# What I expected to happen
1. See a new screen I hadn't seen before

# What actually happened
1. "Can you provide a photo?" reappeared with "No" already selected.

I continued and the next page was the download page. Not sure yet what's going on there.

**Comment by nonprofittechy** [comment]
Resolved in  PR #302
