### ISSUE TITLE
209A Complaint Page 2: Children under 1 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#313]
This is non-essential, but it feels a little weird to say children are "zero."  If they are under 1, can we put their age in months? 

![image](https://user-images.githubusercontent.com/63356951/83185554-2833b680-a0f9-11ea-9ea2-a1c622dd6bfd.png)

**Comment by CaroRob** [comment]
Discussing solution in Slack [Docassemble...channel](https://docassemble.slack.com/archives/C7791ATUJ/p1592225022374600?thread_ts=1592220001.374300&cid=C7791ATUJ) thinking name.formatted_age()
