### ISSUE TITLE
209A: Date formatting is weird - Year appearing before month/day

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#314]
![image](https://user-images.githubusercontent.com/63356951/83186206-2b7b7200-a0fa-11ea-87e9-0fd6b073ee2d.png)

![image](https://user-images.githubusercontent.com/63356951/83186239-36ce9d80-a0fa-11ea-903f-124c45ad2659.png)

**Comment by nonprofittechy** [comment]
@CaroRob ? This was from one your PRs

**Comment by nonprofittechy** [comment]
I think the month/day or informal date like "Summer" is better to come first, so I'll change this.
