### ISSUE TITLE
209A - Relationship to [person] screen

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#328]
On the “your relationship to [person]” screen:
Currently says: “You may think you are not members of the same family or household. But the law says you are.”
I got a little confused when I read this - - would it maybe be better to say “You may think you are not members of the same family or household, but the law might say that you are.”

**Comment by nonprofittechy** [comment]
This is already on @CaroRob's radar, I think fix is pending a merge of the branch she's working on. Don't recall if we had an issue for it yet, will leave open for now

**Comment by CaroRob** [comment]
Yes, DV advocates also flagged and suggested very similar language - this edit is in the NorthEastandMOVA branch.

**Comment by nonprofittechy** [comment]
6a8e056
