### ISSUE TITLE
209A - Navigation between screens (using back/next)

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#329]
I clicked BACK from the “your relationship to [person]” screen to go back to the “what to expect screen” – that worked fine.  But when I clicked NEXT from the “what to expect” screen, it skipped the “your relationship to person screen” and went straight to the “do you and [person] have any children together” screen/question

**Comment by nonprofittechy** [comment]
back/forward navigation fundamentally works in an unexpected way in docassemble; don't think this is the kind of error we can investigate.
