### ISSUE TITLE
General: identify how to handle multiple sittings of Superior Court in one County with unambiguous names

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#331]
On the screen where you select which court you would like - some courts were on the list twice (e.g. Middlesex County Superior Court, Plymouth County Superior Court)

**Comment by nonprofittechy** [comment]
Some courts are listed twice because they have two or more sittings (Superior Court has multiple sittings per county) and do not have unique canonical names for each sitting. We do need to identify how to label those courts and also how not to break things that depend on exact court name match.

**Comment by nonprofittechy** [comment]
From past conversation on Slack: it's not clear which sitting you can file in. But it does seem in most counties with multiple Superior Courts, only one court is for civil matters

**Comment by nonprofittechy** [comment]
The newest behavior in https://github.com/GBLS/docassemble-MACourts/blob/b36405e206e3ac0e8fdbf2d455efe8b808982b95/docassemble/MACourts/data/questions/courts_tester.yml shows a good way to handle this. Append city name to the court name in the selector; include court description which likely says whether it handles civil or criminal cases; doesn't require any functional changes in the code.
