### ISSUE TITLE
209A: Maybe need addendum for defendant race question? 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#333]
If selecting multiple races for defendant, it doesn't fit in the box.  Should this trigger addendum? 
![image](https://user-images.githubusercontent.com/63356951/83769800-498f2800-a64e-11ea-8382-7c02b021debf.png)

**Comment by nonprofittechy** [comment]
I think we settled on Slack:

1. Change to a single-choice dropdown or radio, and shorten race/ethnicity labels
2. Add a field for "other information about race" and put that in the larger text input at the bottom, not an addendum that the police might not see.
