### ISSUE TITLE
209A: Concerned about Under 18 plaintiffs

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#338]
I started a slack discussion, but I am really concerned about how we are addressing under 18 plaintiffs.  Right now, we ask as an early question if someone is completing this form for themselves or someone else very early.  Then we ask if they are over 18 later.  If you said you were completing this form for yourself and then say you are under 18, the interview ends.  I really don't think this is clear and will result in people who should be able to use the interview not being able to.  

I can see many scenarios in which a parent might be completing the interview side by side with their child and would therefore select "I am completing this interview for myself" because they are working with their child, but then the interview would because the child is under 18.  The implications of saying you are completing the interview for yourself are really not clear as is.  I think we should re-instate asking if a parent or guardian is helping after someone says that they are under 18.

**Comment by nonprofittechy** [comment]
6a8e056
