### ISSUE TITLE
209A: Complaint Page 2: list of schools is shown as a regular list, not comma_list()

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#339]
There's some stray brackets showing up in the school/daycare question, when it should be blank. 

![image](https://user-images.githubusercontent.com/63356951/83778401-ac85bc80-a658-11ea-95a9-8d74515d4b21.png)

**Comment by CaroRob** [comment]
I entered a name and address - no bracket, will try again with no daycare or school

**Comment by nonprofittechy** [comment]
I think this was fixed in an earlier commit but not flagged. It used to directly reference an array but now we use comma_and_list() around it.
