### ISSUE TITLE
209A: Add character length limits to text fields that do not have addenda

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#346]
Some fields' overflows need to be handled in order to give crucial information to the court/police. Currently expressed priorities:

- [x] Defendant info form (to go in 'additional information' box)

**Comment by CaroRob** [comment]
Note: abuse_suffered_date – PDF says it will only take a date, but I thought date was coming from Affidavit which allows user to say something like last Christmas, 2019 or something like this. I have a vague memory that this was resolved somewhere, but just checking here.
Page 2 looks like there is some code that accounts for overflow of all text fields into addendum so we do not need character limit for these fields, or do we?
