### ISSUE TITLE
209A: Add "I don't know" option to gun question 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#349]
Feedback given to David that David (and I) agrees with: 

"I just reviewed the whole program using a hypothetical.  I think it’s great.  The only feedback I’d give is in the part where the program asks if the defendant has access or possession of the following:  1. Gun, 2. Ammo, 3. FID Card, 4. License to Carry or 5. None of the Above.   

I know these are the options taken directly from the forms, but there should be a 6th option: “I Don’t Know.”  I’ve assisted many victims who just don’t know if the defendant has access or possess...and I’d write next to the option that they don’t know.  

The program will NOT let you go to the next question without answering one of the options.  So, without a 6th option, the victim can’t proceed to the next question if they don’t have knowledge of defendant access/possession."

**Comment by CaroRob** [comment]
I included this issue in a comment on my branch, NorthEastandMOVA - hoping that when we merge we can included that change. This may also apply to similar questions in defendant information.
