### ISSUE TITLE
209A oath

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#353]
After feedback from prosecutor re admissibility of 209A affidavits in criminal proceedings, we decided that we need to change the way that users swear their statement under oath.

1) give warning that affidavit will be under oath before user begins to write.
2) right before user signs, make them affirmatively check a box that they are swearing to the facts under the pains and penalties of perjury.

**Comment by CaroRob** [comment]
1. We already do give warning that affidavit is under oather before user begins to write.
See below, although in our our Affidavit now we say, "declaring" we should say "affirming or swearing"?

> Finally, as you write your affidavit, keep in mind that when you sign your name at the end of this guide, you are declaring, “{under penalty of perjury}” that your answers to all these questions are {true to the best of your knowledge}.

> under penalty of pejury:
>       means you swear that what you write is true, as far as you know.
>       Swearing "under penalty of perjury" means the court can punish you if what you write is not true to the best of your knowledge.
>       The court cannot punish you if you write about things you saw, heard, or felt.
>       The court cannot punish you if you have good reason to believe that what you write is true.

> true to the best of your knowledge
>       Something is true "to the best of your knowledge" if you were there and saw, heard, or felt it. Something is true to the best of your knowledge if you have good reason to believe it is true.

**Comment by CaroRob** [comment]
2 Move the question in the Affidavit in Support of Request for Child Support, closer to actual signature screen?

This is what have in child support yaml:

```
question: |
  Signing Under Oath
subquestion: |
  Your child support affidavit must be signed "under penalties of perjury."  This means that it can be a crime if you lie on the form.
fields:
  - no label: users[0].states_above_true
    datatype: checkboxes
    minlength: 1
    choices:
      - I promise that my answers on this form are the truth under penalties of perjury
    validation messages:
      minlength: |
        You cannot keep going unless you agree that you will tell the truth.
```
What if we move this to just before signature screen and list the forms that require this agreement? or just say these forms, or 209A application? Modify the child support questions with a reminde that user must tell the truth?

**Comment by kateleebarry** [comment]
It looks like “declare” is the word used on the actual affidavit form, so I think we’re fine keeping declare.

**Comment by kateleebarry** [comment]
I agree with moving that question from the CS affidavit to write before the signature. I would do it immediately before the signature, after the preview screen, that way the user has had a chance to review the form in its entirety before swearing to it under oath.

**Comment by kateleebarry** [comment]
The affidavit itself states that the plaintiff is swearing that the affidavit and all attached forms are under oath, so I think we should just say everything was under oath, not specify which forms were under oath.

**Comment by CaroRob** [comment]
cool declare for Affidavit, and child support says "state or affirm" so declare works for that too. I don't see "under oath" I only see p & p and to the best of my K.  where is under oath? Am  I reading too quickly?

**Comment by kateleebarry** [comment]
You’re not reading too quickly, I’m being lazy and using under oath as shorthand for P&P of Perjury and all that.

**Comment by CaroRob** [comment]
Ok that's great so we can almost use exactly what we have just move the one question to before the signature question. Maybe put something similar to affidavit question about p&p in front of questions about plaintiff's aff in support of req. for cs, and also in the question we move, identify in terms one more time pains and penalties of p, as well as best of your k.  - then we are good to go.
