### ISSUE TITLE
209a: format currency values with thousands separator, no decimal point

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#357]
![image](https://user-images.githubusercontent.com/7645641/84556423-b6f72480-acf0-11ea-8719-4456890ecbc5.png)

dollar figures should all be .00, not .0

**Comment by CaroRob** [comment]
Rather than putting in 2 decimal places on amounts,  same problem on page 1 J 5.when asked how much defendant should compensate plaintiff, let's **not use any decimal places at all** and just round to integers.

**Comment by nonprofittechy** [comment]
I'm also thinking we should have a thousands separator
