### ISSUE TITLE
209a: User feedback from hawcdv.org

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#366]
# Survey result on row 87

**Report type:** I'd like to tell you something else.

**Contact info**: rosiecb@hawcdv.org

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:
The interview questions are very helpful! I just made a few notes/minor suggestions while I was going through.

-- When testing it out, I answered that I would like visitation. When I got to the court selection page I don't think there was a reminder that visitation could only be granted by Probate. It could be helpful to have a prompt if someone selects visitation, it would be easy to forget by the time you get to court selection.

-- On this page: 
When you ask the court for an abuse prevention order, the judge can do 3 things:
1. Deny your request. Refuse to give you a restraining order. John will not get any notice that you asked the court for a restraining order.
2. Make a temporary order. The 2nd hearing will be within 10 days of the temporary order. At the 2nd hearing the judge can hear from both you and John at the same time.

It might be helpful to have it state more explicitly that the temporary order grants protection until the 2nd hearing.

-- At the end when you preview the doc it's still editable, but the changes aren't saved. People may try to make edits that won't be saved when they download 

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
See #288
