### ISSUE TITLE
Hamburger menu doesn't work on phone

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#367]
# User feedback on row 3

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Form** | Housing TRO
**Question** | Sign on your phone 
**Actions** | I tried to tap the hamburger menu button
**Expected** | I thought the menu would open
**Actual** | The whole top bar shifted up and down, and the hamburger menu button didn’t open up a menu 
**Feedback** | It’s Maeve on iPhone 7 software version 13.4.1! I have a video of this if you want. 

---

### Confusion feedback

Question | Answer
---|---
**Form** | 
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Uncategorized Feedback

---

**Comment by nonprofittechy** [comment]
@colarusso this is related to #308 -- can we get this CSS change in?
