### ISSUE TITLE
209A: Relationship with Defendant Screen

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#376]
From Slack:

![image](https://user-images.githubusercontent.com/63356951/84804519-e9df3800-afd0-11ea-99aa-cdc311831e54.png)

1) Change "dating" options to "I am dating Defendant" and "I used to date Defendant"
2) Change center alignment to left alignment for the marriage questions. 

I think this was all our conclusions from Slack?

@CaroRob @nonprofittechy

**Comment by CaroRob** [comment]
Yep - mine.

**Comment by CaroRob** [comment]
[ccfb1c1](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/commit/ccfb1c147b454736b90d6382fc256d88034dd544) Language-impoundment-draft1 branch
