### ISSUE TITLE
209A: Impoundment language - I think this is semi-urgent 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#378]
We need to change the language in the impoundment section specifically: 

"If you asked the court to order John to keep away from any address, the court will not impound that address."

and 

"But if you asked the court to order John to stay away from your home, work or school, John and John’s lawyer the order will show the address John must stay away from."

I would suggest something like:

The Court can keep an address secret from the Defendant even if you want the Defendant to stay away from there.  Your restraining order will order the Defendant to stay away from your address "wherever that may be."

**Comment by CaroRob** [comment]
Excellent that is on one of my lists somewhere to ask you, will include in next language commit.

**Comment by nonprofittechy** [comment]
great, I will leave this alone then :)

**Comment by CaroRob** [comment]
My thoughts on this started to get too long to fit here and I think it needs some discussion. Created a  [Google Doc with same title and number as this issue](https://docs.google.com/document/d/1Xwq2FZ5a0jyiTtWK5VYzXUno5_y_dSiZC-E6mmXmn10/edit?usp=sharing) to discuss... and work on language. I am taking out the language @kateleebarry suggests today and do a pull request so what we have isn't wrong, and then hope to refine language going forward.

**Comment by CaroRob** [comment]
just pushed a PR with first draft to address the urgency of this issue. [ccfb1c1](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/commit/ccfb1c147b454736b90d6382fc256d88034dd544)
