### ISSUE TITLE
209A: Only trigger gun addendum if > 40 characters

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#380]
Addendum is triggering from the gun question on Page 1, but all the info fit on the complaint and the addendum doesn't include any additional information. I don't think I'm doing a good job describing it, so I'm just attaching the file. 

[Addenda 209A.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4788762/Addenda.209A.pdf)

**Comment by kateleebarry** [comment]
~~Same with the school questions on Complaint Page 2.~~

~~This was from Michelle's skipper version of the 209A if it makes a difference.~~
 (opened new issue for this)

**Comment by nonprofittechy** [comment]
I think I was assuming we would always want the names of the guns to go on their own page. But I can adjust so it uses a character limit instead.

**Comment by CaroRob** [comment]
~~I got an addendum for no contact - empty when I said defendant can contact my kids~~ opened new issue for this
