### ISSUE TITLE
Court service center feedback re 209A affidavit 

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#381]
# Survey result on row 90

**Report type:** I'd like to tell you something else.

**Contact info**: mary.klaes@jud.state.ma.us

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:
For the affidavit, I'm not sure that having each incident separated out is helpful? When interviewing the person, sometimes she went back and forth, so it might be helpful to have the Affidavit component more open ended?- i.e. maybe start with the most recent date, then ask if there have been more incidences? When I was working on this for the first time, I didn't anticipate having to go back in separately and I just kept writing her story, then realized after we completed the Affidavit portion that there were separate inputs for each incident. Maybe as I work with this more, I won't have the same feedback- first impression from first time using!

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
@CaroRob
