### ISSUE TITLE
209A: Create an instruction sheet with info

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#409]
E.g., after 4:30 call your local police station and get it handled right now.

**Comment by kateleebarry** [comment]
Suggested instructions - something like 

- If it is between 8:30 AM and 4:30 PM on a weekday (excluding state holidays), you should call your court at [number] and tell them you have completed a 209A application that you need to file.  The court will give you instructions that you should follow.
- On weekends, weekdays after 4:30 PM, or if it is a holiday, you should take your application to your local police station and tell them you want to file for a restraining order.

**Comment by CaroRob** [comment]
Not to  make more work - but docassemble can tell when the person thinks is planning on filing.

Can we make the language Kate suggests conditional on when a person says they are planning to file?
Also teeny readability edits for Kate's:
To file your 209A:
- Monday-Friday, but not holidays,  
   8:30 AM - 4:30 PM,
   Call [your court]:  [number].
   Tell them you you need to file a 209A application and that you already completed it. 
   They will give you instructions that you should follow.

- Weekends and holidays,  or 
   Any day **after** 4:30 PM, 
   Take your application to your local police station. Tell them you need to file for a restraining order.

If saving for filing later:
   use Kate's language, edited above, 
Else if courts are open:
 depending on when they say they plan to file:
 Courts open: 
   The courts close at 4:30 today.  Call [your court]:  [number] before 4:30.
   Tell them you you need to file a 209A application and that you already completed it. 
   They will tell you what to do next.
Courts closed:
   The courts are closed.  Take your application to your local police station. Tell them you need to file for a restraining order.

Actually, I think we need to see if we can put together a rough description about what to expect.
The clerk at the court you call may tell you 
how to file
you will have a remote hearing over the phone or using Zoom, a program you can use for video calls.
_Working with BBA and VLP to put together some info about remote hearings we can simplify and adapt remembering to include protecting yourself by hiding or disguising your background_
After your hearing if the judge decides to order a restraining order, the police will serve ${other_parties.familiar()}..... etc. I don't think we have anything on this on MassLegalHelp, Quinten already  mentioned that we should. I will get right on it. but I think in the instructions/209A cover sheet we should definitely include something about service after the hearing....

**Comment by nonprofittechy** [comment]
I have some language like Caroline suggests above in the download screen I put in the https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/tree/209a-review-screens branch. I should separate out that into its own branch

**Comment by CaroRob** [comment]
Just a thought - when plaintiff gets forms, Affidavit has a space for Witness at the bottom - in case they notice this - I think we ought to address it - probably in this cover page - just jotting down here to keep a record of stuff we want to put in cover sheet

**Comment by CaroRob** [comment]
Indicate in Page id: signature date, v0.96 - that plaintiff does not need to put in a filing date at all - they can save for later.

**Comment by nonprofittechy** [comment]
Resolved in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/513
