### ISSUE TITLE
209a: Remove carriage returns in "persons authorized" field

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#411]
"persons authorized by plaintiff to have access to this confidential info" field

field allows me to press return and type names in list format, rather than be separated by commas, etc.  Added a wide space between the two names when I entered in two names. (see example) 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/66283360/85319495-73ca4d80-b476-11ea-8fc3-453ca11e111f.png">

**Comment by nonprofittechy** [comment]
stripping `\n` from this field in attachment block.
