### ISSUE TITLE
Clear signature option is missing on iPhone

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#416]
# Survey result on row 91

**Report type:** A test case (qa)

**Contact info**: It's Mia!

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1jNZ8KdLKDuK45g-3mL2LJSQmuQ2NM8YOdM_J6lxYpBY/edit#gid=850505213
**Test id** | GMF Family Law, Test Case 01, Run 01 - Interview row: 128
**Tester** | MiaBonardi
**Question** | Please Sign Below
**Input** | I was signing on my iPhone and there was no "Clear Signature" option. 
**Expected** | Clear signature option present
**Actual** | No clear signature option present
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
If this can be replicated it is an upstream issue. @miabonardi willing to ask and replicate on the Docassemble Slack channel?
