### ISSUE TITLE
basic-questions: rephrase "next 15 minutes" to "the next few minutes"

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#420]
# Survey result on row 93

**Report type:** A test case (qa)

**Contact info**: It's Mia!

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1jNZ8KdLKDuK45g-3mL2LJSQmuQ2NM8YOdM_J6lxYpBY/edit#gid=850505213
**Test id** | GMF Family Law, Test Case 01, Run 01 - Interview row: 157
**Tester** | MiaBonardi
**Question** | Your form will be sent within the next 15 minutes.
**Input** | Tap to continue 
**Expected** | Tap to continue 
**Actual** | There was no unexpected behavior. While this may not be an MVP issue, I think the "15 minutes" might be too specific and the phrasing could be more general for this screen. See photo. 
**Link** | 
**Pic** | https://drive.google.com/open?id=1exRO6IeckxmnGBEbAU7ZDbH4qBPiA5Lr
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
@miabonardi this could be a good PR for you to make

**Comment by miabonardi** [comment]
This screen is no longer in the GMFMVP code. However, the screen in basic questions still says, "We will deliver it securely. Please allow up to 15 minutes for the email to arrive." `Page id: ready to email, v1.0.10, (playground), dev`
