### ISSUE TITLE
209A: Don't ask if Defendant is parent of children of care

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#427]
Discussed with Caroline.  This shouldn't affect anything. Don't give CS or custody options for these kids, just no contact, and for that it doesn't matter if defendant is parent.

**Comment by CaroRob** [comment]
@kateleebarry - sorry, just quadruple checking - We have a note under defendant is other parent question here:

> In some cases, to keep children safe, a judge **can** order ${other_parties.familiar()} not to contact ${other_parties.familiar()}'s children. But it is complicated to convince a judge to make this order.
>       
>       You may have to file a guardianship case also.  [Talk to a lawyer](https://MassLegalHelp.org/find-legal-aid) if you need the judge to order ${other_parties.familiar()} to have no contact with this child.
>     show if: children_cares_for[i].defendant_is_parent

This makes it look like we should keep defendant is other parent? and include note. If we omit question, plaintiff could end up asking judge for no contact with child they care for,  when defendant is parent? I mean they can anyway as it is - but maybe they should know unlikel to get no contact order? 

Responding to issue now whilst @kateleebarry is ill, hoping to check w Jamie or someone else - just want to record thoughts here so we have them when question arises again.

**Comment by CaroRob** [comment]
See #458

**Comment by CaroRob** [comment]
Slack conversation w @kateleebarry 11 Sept, 2020

```

> CR: Did we decide absolutely that we do not want to ask if defendant is parent of child plaintiff only has responsibility for - even if it means plaintiff may end up asking for no contact and having  a difficult time getting a judge to order this? At one point we had a note that popped up and suggested plaintiff get legal advice or help if they wanted to ask for no contact in this situation..... I am happy to leave it as is without asking but didn't want to close the issue if we were leaving it as a possibility. Your thoughts?
> Kate: I think we decided not to ask
