### ISSUE TITLE
209A: Impoundment/addresses/confidential information form issues - high priority 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#428]
There's some new issues with the plaintiff's addresses/keeping addresses secret/impoundment:

We ask:

- Stay away from: Home, Work, School
- Do you want to keep each of those addresses secret
- We (should) ask for each of those addresses on the plaintiff confidential information form
- We ask whether to impound addresses.

Currently, if you say you want to keep the work and school addresses secret, we do not ask for these addresses and they do not appear on the plaintiff confidential information form.  We MUST put those addresses on the plaintiff information form is the plaintiffs wants a stay away from those addresses, even if those addresses are impounded and/or kept off the order.

The plaintiff information form should not interact in any way with the decision to (a) keep addresses off the order or (b) to impound addresses.  Think of the plaintiff information form as impounded by default.

**Comment by kateleebarry** [comment]
I think ideal (maybe post-mvp) flow here would be:

- Ask which addresses plaintiff wants stay away from
- For each address plaintiff wants stay away from, ask whether to keep secret
- If plaintiff says they want an address secret, automatically check the "impound" address box on the impoundment motion
- Always ask plaintiff's home address and include on plaintiff information form.  
**- Also always include work or school address if plaintniff wants stay away from that address.  This is regardless of decision to include on order or to impound.  (This part really needs be MVP).**

**Comment by CaroRob** [comment]
Always ask plaintiff's home address and include on plaintiff information form.
- Also always include work or school address if plaintniff wants stay away from that address. This is regardless of decision to include on order or to impound. (This part really needs be MVP).
In PR [fixed issue where plaintiff addresses and information were not asked …#454 ](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/454) It worked when I tried it 2-3 times, but could use testing
