### ISSUE TITLE
Broken link + Sign in, register, download issues Bentley UX row 48

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#439]
"- 209A Restraining Order link also has a link for How Can a 209A Order Help Me? that seemed to go nowhere.
- I wasn't sure if I really needed to Sign-in or register to save my work, since it said ""optional."" This could be more clear. Also, why is Sign-in captitalized and register not?"

**Comment by nonprofittechy** [comment]
![image](https://user-images.githubusercontent.com/7645641/86199421-15613700-bb28-11ea-8ee8-adab38029a49.png)

I think this is the correct capitalization for the beginning of a sentence. On second look at this though, it may not be 100% clear what the word "optional" is modifying. Maybe we can drop it

**Comment by CaroRob** [comment]
Yep - I would just take out the word in parens ;) as per readability tip xxx, "anything in parentheses is not needed - unless it's an acronym>"

**Comment by CaroRob** [comment]
Aah as for part 1 - link not working in term.  Although formatted as a link does not work. Jonathan? or figure out a different way to link?

**Comment by nonprofittechy** [comment]
I think links in terms just don't work. I asked Jonathan about this recently but forgot to go and fix it in our code
