### ISSUE TITLE
General: Improve input for entering a birthdate/other date long in the past

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#447]
https://trello.com/c/LT7qlKFz

**Comment by plocket** [comment]
Current status: Data is being stored. Invalid data is not yet fully handled - invalid birthdates can be created without a message to the user and the invalid date gets changed to a (different) valid date without their knowledge.

- https://github.com/SuffolkLITLab/docassemble-VirtualCourtToolbox/commit/e5ad86e83b3b306f18a4dbaeb2cfff39dd6e048e
- https://github.com/SuffolkLITLab/docassemble-VirtualCourtSampleInterviews
