### ISSUE TITLE
209A: Affidavit of Care - Confidential Address Auto-Fill Bug

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#45]
This is at sections 4 & 5 and 10 & 11 of the form.

- If I select the option that the user **does not** need their address to be kept confidential, it fills it in at section 4, 5 **and** 10, 11. It only needs to be filled in at section 4 and 5.
- If I select the option that the user **does** need their address to be kept confidential, it only fills it in at section 10 and 11. This is correct. However, for some reason, it also fills in the child’s past addresses at section 4. I think this is incorrect.

I'm not sure what to link to but this is where the [question first comes up](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/241da79f6d87cd3cc1031988a45713c4d585c05e/docassemble/MAVirtualCourt/data/questions/209A_affidavit_disclosing_care_or_custody_proceedings.yml#L592) in the code.

**Comment by brooksmk** [comment]
Should be fixed in this pull request: https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/52
