### ISSUE TITLE
209a: date of abuse does not fit on PDF

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#457]
# Survey result on row 98

**Report type:** A test case (qa)

**Contact info**: Sinéad Vaughan

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1EMtbq4tiUWXh0dR8HwWu_nEuMyqRBsY6ShGDk-782ks/edit#gid=1836369613
**Test id** | 209 A, Case 2.4 - Interview Row: 31
**Tester** | sineadvaughan
**Question** | Issue 1- This was not something asked specifically to test. The title of the screen 'Last time of abuse'. Issue 2 - 'Why should the judge order [defendant] not to contact your child?'.
**Input** | Issue 1 - Filled in the last time the applicant was abused.
Issue 2 - Enter A LOT of text in the 'Why should the judge order [defendant] not to contact your child?' field (we want to see what happens if an excessive amount of text is entered into this field and how it shows up on the pdf form) Row 31 Cell AL.
**Expected** | Issue 1 - I expected the field to be fully visible when filled out, saying 'last summer, 2011'.
Issue 2 - I expected to be able to fill in the field fully and have the information fully visible.
**Actual** | Issue 1 - The information in the field was not fully visible, 'last summer, 200' was what was in the field.
issue 2 - The information that I filled in was not visible.
**Link** | 
**Pic** | https://drive.google.com/open?id=1iyvk5ebqdjPDKMq4cHAUhS5OuVa0r8RB, https://drive.google.com/open?id=1lX5QRKODiOTM-xWxWKKLdZas7v7FWcwA, https://drive.google.com/open?id=12oD7Y3Ekri0s7KHn3qLcxu96rR00SlBX
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Suggestion: we keep line height normal to avoid crazy large font, but set this field to auto-size. I don't think we need to limit number of characters.
