### ISSUE TITLE
209A: not asked if defendant is parent for child that plaintiff takes care of but is not parent of

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#458]
Internal: A test case (qa), row 99

# Survey result on row 99

**Report type:** A test case (qa)

**Contact info**: Aubrie Souza - Slack/ Zoom

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1EMtbq4tiUWXh0dR8HwWu_nEuMyqRBsY6ShGDk-782ks/edit#gid=1836369613&range=N54
**Test id** | 209A, Case 2.26, Row 54, Column N
**Tester** | aubriesouza
**Question** | "For your child in your home who you care and take responsibility for is [defendant] the child's parent?
**Input** | Selected Yes to question is there a child in your home under 18 which you care for
**Expected** | Expected to be asked - "For child in your home who you care and take responsibility for.....is [defendant] this child's parent?"
**Actual** | This question was not asked and I could not answer Yes. 
**Link** | ? Do not see link 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
@aubriesouza --this is expected if you answer **no** when asked if the Defendant is the parent of any of the Plaintiff's children a few screens earlier in the interview. Can you confirm this behavior when you answer "yes" to the defendant being a parent of one of the children?

**Comment by aubsticle** [comment]
@nonprofittechy Following the prompts for this scenario I answered **No** when asked "Do you and [defendant] have any children together]?"  **Yes** to "Are you responsible for any other children under 18 who live with you?, and was not asked "For child in your home who you care and take responsibility for is [defendant] this child's parent?" and it goes straight to asking "Do you and [defendant] live in the same household. 

The testing scenario as written expects the interview to ask specifically whether the defendant is the parent of the child under 18 who is not "my child".  I've redone it a few times and have an abbreviated recording of the behavior. https://drive.google.com/file/d/1H5YjupGSsQKy1vZ7JgnIFCrMyZnJoBFU/view?usp=sharing

**Comment by nonprofittechy** [comment]
my understanding is that we will be taking out this question. Leaving this open for now--I think this is post MVP

**Comment by CaroRob** [comment]
Slack conversation w @kateleebarry 11 Sept, 2020

```

> CR: Did we decide absolutely that we do not want to ask if defendant is parent of child plaintiff only has responsibility for - even if it means plaintiff may end up asking for no contact and having  a difficult time getting a judge to order this? At one point we had a note that popped up and suggested plaintiff get legal advice or help if they wanted to ask for no contact in this situation..... I am happy to leave it as is without asking but didn't want to close the issue if we were leaving it as a possibility. Your thoughts?
> Kate: I think we decided not to ask

```
