### ISSUE TITLE
209A: Affidavit of Care - Previous or Pending Care/Custody Cases

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#47]
There are currently only **two** options: 

- ['I have been part of another case involving…](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/241da79f6d87cd3cc1031988a45713c4d585c05e/docassemble/MAVirtualCourt/data/questions/209A_affidavit_disclosing_care_or_custody_proceedings.yml#L761)’
- ['I was not part of any other case, but I know about another case involving …’](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/241da79f6d87cd3cc1031988a45713c4d585c05e/docassemble/MAVirtualCourt/data/questions/209A_affidavit_disclosing_care_or_custody_proceedings.yml#L763)

I think that needs to be a third option: 

- ‘I was not part of any other case and I don’t know about another case involving…’ which would then skip asking about previous or pending cases.

**Comment by kateleebarry** [comment]
I agree

**Comment by brooksmk** [comment]
@kateleebarry option 3 shouldn't show up if this form is filled out during the 209A process, right? Only if this is a standalone form?

**Comment by kateleebarry** [comment]
I think it depends a little on how they are stitched together - but theoretically in a 209A someone should only be filling out this form if they've answered yes to there being related care or custody proceedings on Complaint Page 2, in which case option 3 wouldn't be necessary in those cases. But this form is used in many other family law contexts, in which case Option 3 would be necessary.

**Comment by brooksmk** [comment]
Thanks, Kate. @nonprofittechy I'm @'ing you here so you can take a look at this conversation. Should I go ahead and implement 'option 3', or leave it out for now since we're only focusing on the 209A right now?

**Comment by nonprofittechy** [comment]
It sounds like the idea is to change it to radio buttons, which makes sense to me. We have checkboxes, and you can leave both checkboxes empty right now. But I know Caroline had some ideas to change the language here already. I'll keep in mind that 2 options are unclear without a third choice right now.

**Comment by nonprofittechy** [comment]
Resolved in 
36ab8b5
