### ISSUE TITLE
209A: Attorney Representation Repeat Questioning

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#48]
- **What I did:** I selected that the attorney represented all the children and selected 'continue'.
- **What I thought would happen:** I thought I would go to the next question
- **What actually happened:** I got the same question over again. 

The workaround to get past the question is to select that the attorney did not represent all children and then select the child that the attorney represented.

Here's the [link to the screen](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground11MMMA%3A209A_affidavit_disclosing_care_or_custody_proceedings.yml&session=poLJlmvHxSxwfXn0Gm60KP7iEHxC2Imo) it happened on.

<img width="327" alt="Bug" src="https://user-images.githubusercontent.com/49881041/80544968-895d5280-89b2-11ea-940e-a05b7a879229.PNG">

**Note:** The same thing happens at the [GAL/investigator screen](https://apps-dev.suffolklitlab.org/interview?i=docassemble.playground11MMMA%3A209A_affidavit_disclosing_care_or_custody_proceedings.yml&session=poLJlmvHxSxwfXn0Gm60KP7iEHxC2Imo).

<img width="301" alt="Bug2" src="https://user-images.githubusercontent.com/49881041/80545347-6b442200-89b3-11ea-8cb3-e0de65acc278.PNG">

**Comment by brooksmk** [comment]
Should be fixed in this pull request: https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/52
