### ISSUE TITLE
after 2nd incident in affidavit, question reads "most recent abuse"

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#487]
# Survey result on row 104

**Report type:** I found a bug.

**Contact info**: Caroline

---

### Bug

Question | Answer
---|---
**Question** | Page id: 209A Incident Summary, v0.96
**Actions** | This is supposed to be a summary of all the incidents of abuse I have described in the in the Affidavit
**Expected** | I expected the question at the top to say something like Your Affidavit or A summary of abusive incidents you have described or something to that effect - have to look it up in the code
**Actual** | I actually entered 2 incidents, after the 2nd incident when the screen allowed me to see my descriptiosn of both, the heading continued to read The most recent abuse - this question should be conditional so if more than one incident...
**Feedback** | We always race through the affidavit - maybe we need to test the affidavit more thoroughly before release.

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by CaroRob** [comment]
I will give this a try in language edits - first I want to finish up  defendant information characater limits - thought I was further along!

**Comment by CaroRob** [comment]
I just fixed this in language-edits2-mvp , haven't finished commits, but it works in my branch locally, turns out it was a couple of things.
