### ISSUE TITLE
209A: Affidavit of Care - Attorney  and GAL information

### ISSUE THREAD

**Issue by maevemacglinchey** [SuffolkLITLab/docassemble-MAVirtualCourt#49]
1. Empty parenthesis in this space when there is no information submitted.
2. When there is information submitted re: name of attorney, it puts in the name of the attorney and leaves the parenthesis empty.
3. When there is information submitted re: name of the GAL, it puts in the name of the GAL and repeats the GAL’s name in the parenthesis.
4. Is the name of the children they represent supposed to go in the parenthesis? (It doesn't at the moment)

**Example of 1:**
<img width="537" alt="1  No information submitted" src="https://user-images.githubusercontent.com/49881041/80543809-00ddb280-89b0-11ea-8290-9e7a04fe1054.PNG">

**Example of 2:** 
![image](https://user-images.githubusercontent.com/49881041/80545794-7c416300-89b4-11ea-8622-4f44d8f0dae6.png)

**Example of 3:**
![image](https://user-images.githubusercontent.com/49881041/80545725-54ea9600-89b4-11ea-8c41-e08cfa468e8b.png)

**Comment by brooksmk** [comment]
Should be fixed in this pull request: https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/52
