### ISSUE TITLE
Internal: GMF review page not working, row 114

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#503]
# Survey result on row 114

**Report type:** A test case (qa)

**Contact info**: 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1MTEOxXVMGbj5dtaNGFXarpSldTej99OHP7_33YW76d8/edit?usp=sharing
**Test id** | GMF Family Law, Test Case 01, Run 02 - Interview row: 127
**Tester** | MelanieRush
**Question** | Review of your answers
**Input** | Link to make changes to past entries
**Expected** | Review form option loads
**Actual** | the review of answer page loads, but the sections do not appear
**Link** | 
**Pic** | https://drive.google.com/open?id=1FcjontBIIFKrCqxXgaz3zEEHYKSYX9Ve
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by miabonardi** [comment]
This test overall failed and was redone because it was not done on a phone and the subsequent tests passed.
