### ISSUE TITLE
Internal: GMF unexpected emergency text on preview, row 115

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#504]
# Survey result on row 115

**Report type:** A test case (qa)

**Contact info**: 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1MTEOxXVMGbj5dtaNGFXarpSldTej99OHP7_33YW76d8/edit?usp=sharing
**Test id** | GMF Family Law, Test Case 01, Run 02 - Preview row: 13
**Tester** | MelanieRush
**Question** | PDF Preview
**Input** | 
**Expected** | I am asking the Court to give me sole legal and physical custody of my children. I would like the other party to have parenting time every other weekend from Friday at 6 PM through Monday at 9 AM.
**Actual** | I am asking the Court to give me sole legal and physical custody of my children. I would like the other party to have parenting time every other weekend from Friday at 6 PM through Monday at 9 AM.
Plaintiff asks that this motion be heard as soon as possible by remote hearing as Plaintiff has demonstrated exceptional or exigent circumstances, as contemplated by Standing Order 2-20.
**Link** | 
**Pic** | https://drive.google.com/open?id=1lVLiu-sAizkAKFf-5UK5Bu5R0DIRh1tN
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by plocket** [comment]
Did this get taken care of, @miabonardi ?

**Comment by miabonardi** [comment]
@plocket I don't exactly understand what went wrong here and where but this test overall failed and was redone because it was not done on a phone and the subsequent tests passed.
