### ISSUE TITLE
2nd school address does not show up on Plaintiff Confidential Form addendum, but 1st school does

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#519]
1st work address shows up on addendum and Plaintiff Confidential Information form, 2nd does not show up.
1st residential address shows up on Plaintiff Confidential Information form, and 2nd residential address shows up on addendum - I will follow this model to fix school and work addresses.

**Comment by CaroRob** [comment]
Tried to fix this morning and couldn't. Have some ideas but ran out of time. I might be able to one day, but got taxes to do this weekend.

**Comment by plocket** [comment]
Might this have been a problem with how the test was written and run/how the interview is written? There are two places to say whether you want to keep your addresses private/impounded or whatever:

1. One question asked 'Do you need to keep your addresses and phone numbers private?' The test said to answer 'Yes', so the tester (me) did.
2. There was a previous question asking approximately "Which addresses do you want to keep private?" The test said to mark everything not mentioned on the test as 'no' or no answer, taking the shortest path. I followed those instructions too.

Could that have been the problem? The code looks like it's doing the right stuff.
