### ISSUE TITLE
209A Cover Sheet: "Congratulations"

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#526]
This is not MVP.

As I think about it, I'm not sure how I feel about the word "Congratulations!" at the top of the user's cover sheet they get when they complete the interview.  It just feels too happy for a domestic violence situation.  Idk. Maybe I'm wrong. @CaroRob

**Comment by CaroRob** [comment]
I get it completely - maybe we can do some user testing on this? It's a huge amount of work to get through emotionally as well as in other ways - would like to give users some positive encouragement - maybe we can check with some survivors to see what they think - I don't mind taking it out for now and asking people about putting it in..... or testing with people with it in and see what they say they feel.
Either way I am ok with whatever you want us to do.
