### ISSUE TITLE
When there is only a downloadable form we should consider splitting instructions and the form

### ISSUE THREAD

**Issue by colarusso** [SuffolkLITLab/docassemble-MAVirtualCourt#534]
When we send forms directly to the court there are two versions of the form: (1) the one that goes to the court with a cover page including sender info; and (2) one that goes to the sender, absent the court's cover sheet, but occasionally with a instructional cover page for the sender. We compile the cover sheets and the forms so folks can easily print, but in the use case where there is no option to file (e.g. 209A) this complicates things because if you forward the form to the court you also are including a cover sheet they don't need. Maybe there could be two attachments in the email. I'm not sure what the best solution is, just flagging the issue.

**Comment by BryceStevenWilley** [comment]
This has mostly been handled with the court bundles that we are adding in the Weaver to new forms. There are still some open questions about what to let people download and how, but most of this issue has been resolved I think.
