### ISSUE TITLE
Internal: with signature, couldn't see 'clear' except in horizontal mode, row 117

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#537]
# Survey result on row 117

**Report type:** Part of the form was confusing.

**Contact info**: When signing the form, the “clear” option only appeared when I switched my phone (iPhone11) into horizontal mode. [Delaney Halvey on Slack]

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | Signing the Form
**Confusion** | I did not see the “clear” option until I tried switching my phone into horizontal mode (iPhone 11)
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by nonprofittechy** [comment]
Upstream change to this in 1.1.71
