### ISSUE TITLE
209A: Addenda issues

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#567]
When I did use the interview yesterday, it triggered an addenda on the defendant information form that really seemed unnecessary, specifically with "other physical characteristics."  It really looked like the text I put would have fit (51 characters), but instead it triggered an addenda.  Also, since this is defendant information, we really should be using character limits, not addenda anyway.

**Comment by CaroRob** [comment]
This should have been fixed before we released - probably a mistake.

**Comment by CaroRob** [comment]
@kateleebarry I believe the **only** addendum we want for Defendant informaton page is if plaintiff uploads a photo. Everything else should all fit onto the one form with no overflow at all?

**Comment by kateleebarry** [comment]
Correct
