### ISSUE TITLE
209A: Child Plaintiff - Get rid of "Are you responsible for children" question?

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#569]
For child plaintiffs, should we get rid of the "Are you responsible for any children under 18 who live with you?"  This seems like a very unlikely circumstance that a child would have guardianship/care of another child.

**Comment by CaroRob** [comment]
I agree, however when I discussed this w Quinten - our adoption alert person - he did think of those occasions although not typical a person who is 16 could have an older spouse and be responsible for spouse's children who is older than plaintiff, but under 18. Strange situation but as I reflect on my experience with Pakistani Muslim women and families this situation is not as far-fetched as it may seem.  I **know** I had the same reaction as you when I first began this path but..... it's really your call or we could consult - particularly maybe with advocates who work with other cultures?

**Comment by kateleebarry** [comment]
That's a good point, sadly.
