### ISSUE TITLE
209A: Incorporating years into affidavit

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#571]
Going through the affidavit again, I put in two different incidents from two different years.  When the affidavit generates though, it doesn't include either of the years.  I know we don't include the year for the first incident because it's up at the top of the affidavit, but I do think it's confusing not to include years for subsequent incidents.  

For reference, the generated text was this (I didn't make any edits or add anything else): 

"On or about Jan. 1, noon house, 

On or about Jan. 1, noon Boston,"

**Comment by CaroRob** [comment]
This is a bug and needs to be fixed, the year and date should go into every incident - until we get to patterns of abuse

**Comment by plocket** [comment]
Closed by #642
