### ISSUE TITLE
Basic questions: id: choose a court

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#575]
change court(s) to court or courts
review help screen
Do we really want to say Only you know the best court to file in? This is not like only you know what is the safest thing to do for your children and yourself in an abusive situation - a lawyer or advocate would probably actually **know** the best court to file in, whereas they would not know the safest path for you to take in an abusive situation.

**Comment by kateleebarry** [comment]
Agreed for the reasons you said.
