### ISSUE TITLE
209A: Date field too small

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#576]
In the last few 209As I've done, some of the date fields have been too small for the dates the way we are formatting them.  Maybe we could switch to mm/dd/yyyy? 

![image](https://user-images.githubusercontent.com/63356951/90696476-559c8600-e24a-11ea-960d-ad3fefab9e9f.png)

**Comment by CaroRob** [comment]
1. Page 1: formatted 9/11/2020, 
2. Affidavit: field is big enough for month dd, yyyy but doesn't show up on preview. 
     2b. Because signature date appears on every other page in the preview, I added it to the affidavit **preview**. I hope this is ok?
3. Page 2: **Reminder page 2.yml is not really page 2!! ergh-**  formatted ("M/d/yyyy"), However in both attachment blocks there are pdf fields signature_date and signature_date__2. The second one is left over from previous PDF which also had an additional copy for Probation - updated PDF application only has 1 sheet for Page 2, so 2nd signature date can be deleted. I neither formatted nor  deleted in this commit. 
4. Plaintiff Confidential Information: field is big enough for month dd, yyyy
5. Defendant Information Form: field is big enough for month dd, yyyy
6. Motion to Impound: field is big enough for month dd, yyyy
7. Affidavit Disclosing Care or Custody Proceedings has date separated out, a separate field for each part of the date, so it works.

**Comment by plocket** [comment]
Closed by #642
