### ISSUE TITLE
Behavior of back button prevented completion of the form, row 12

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#581]
# User feedback on row 12

**Report type:** Part of the form was confusing.

---

### Bug

Question | Answer
---|---
**Form** | 
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Form** | 290A
**Question** | All
**Confusion** | I (advocate) wanted to go back quickly to learn the abusers name (the victim needed a break because of crying children) I couldn't click on "basic info" or "your relationship" sections so I kept pressing the back arrows until i got to the info i was seeking. When i tried to go forward again all the data was lost - 3 children's info , date of abuse, allegations. Very frustrating. We'd already taken a break because she was overwhelmed. She's going to hold off on RO. Perhaps make the tabs available so that user can "jump" to that section. I know it's a work in progress - thank you!
**Feedback** | 

---

### Uncategorized Feedback

---

**Comment by nonprofittechy** [comment]
We implemented review screens and changed label of "back" to "undo" as an interim step. We'll continue to improve this experience in our next milestone. It's not a trivial fix.
