### ISSUE TITLE
Integrated testing: Use template strings to clean up console log

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#596]
Not essential, but you could write this in the form of line 22, which would make it look cleaner, i.e., 

```console.log(`BRANCH_NAME: ${BRANCH_NAME}; pull url: ${installUrl()}`)```

_Originally posted by @niharikasingh in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/592#discussion_r479824323_

**Comment by BryceStevenWilley** [comment]
I'm gonna close this issue, it's so small and I can only find usages of `console.log` in repos that have the same copied code as in this issue, so repos that are still on MAVirtualCourt.
