### ISSUE TITLE
Testing: Use `encodeURIComponent('file name')` to deal with unusual characters

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#598]
Should this be `encodeURIComponent('209a_package')`? Doesn't really matter for this filename, but it will for more exotic filenames with unusual characters.

_Originally posted by @niharikasingh in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/595#discussion_r480440296_

**Comment by BryceStevenWilley** [comment]
Also gonna close this, it seems very specific to code that we're not updating much anymore.
