### ISSUE TITLE
Court selection

### ISSUE THREAD

**Issue by brooksmk** [SuffolkLITLab/docassemble-MAVirtualCourt#6]
Should we handle court selection on a form-by-form basis (209A, housing TRO), subject matter by subject matter (housing law, family law), or in the umbrella interview? Court selection rules can get pretty complicated and can influence what parts of forms can/should be filled out (e.g., visitation-related relief is not available in the 209A context if you file outside of probate and family court)

**Comment by nonprofittechy** [comment]
I'm not convinced we even need the umbrella interview any more.

The static web page David made will do what we need more simply.

We are still stuck with the metadata dictionary idea, but we can definitely
decide court on a form-by-form basis. I think we should think of the
basic-questions as providing a good enough default, but never a ceiling on
how customized we might make a form.
