### ISSUE TITLE
Designing Template for user instructions - next steps

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#606]
CR was to send @colarusso a regular / not template Word 209A instructions file, replacing jinja2 with words, David was going to send to Rose to review and design a template we can use across all interviews. 
CR attaching this to this issue  - 
replaced jinja w green text and all conditional paragraphs are included in file to allow for longest instructions.
[209A_next_steps_for_user 2020-09-04.docx](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/5175688/209A_next_steps_for_user.2020-09-04.docx)

**Comment by BryceStevenWilley** [comment]
@purplesky2016  did a lot of work getting this into the Weaver at https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/pull/348, I think this issue should be good for now.
