### ISSUE TITLE
209A: remove all sentence construction from affidavit section

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#633]

**Comment by CaroRob** [comment]
Left date, time and location in so each incident can begin with this critical info - @kateleebarry and I on the same page for this.

**Comment by plocket** [comment]
Closed by #642

**Comment by nonprofittechy** [comment]
From what I understand we decided to also remove date/time construction. Keeping this open to track that

**Comment by CaroRob** [comment]
I am working on this needs to stay open until we get all the 209Av2 issues to do with Affidavit fixed as they all have to go together.
