### ISSUE TITLE
209A: Consider linking to "https://www.techsafety.org/"

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#656]
Need a little more advice on how to keep your information safe?

**Comment by CaroRob** [comment]
@kateleebarry 
I think this may be information overload.
We tell people to use a safe computer in the first screen - they need a 209A if they are here, not learn how to keep their computer safe. 
The[ link for survivors to keep their tech safe](https://www.techsafety.org/resources-survivors) is a page with about 50 more links to other resources for how to keep safe. I don't think it makes sense to link to any of this in the context of asking the court for a 209A. 
Sorry to be so negative 👎
