### ISSUE TITLE
209A: Defendant Information 209A - Defendant Home Address Misaligned on PDF 

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#67]
In one test I ran, when asked for Defendant's home address I put "(unsure)" in the 'Street Address' field, followed by Kansas City, Missouri 00000 in the city, state, and zip code fields. When transferred to the PDF. a carriage return was put after "(unsure)" so the information no longer fits into the PDF field (see attached PDF). 
[Defendantinformation209a.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4565095/Defendantinformation209a.pdf)

**Comment by nonprofittechy** [comment]
Resolved in https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/280
