### ISSUE TITLE
User: I found a bug., row 44

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#683]
# User feedback on row 44

**Report type:** I found a bug.

---

### Bug

Question | Answer
---|---
**Form** | 
**Question** | Birthday year
**Actions** | 
**Expected** | Enter my birthday
**Actual** | year would not set
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Form** | 
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Uncategorized Feedback

---

**Comment by nonprofittechy** [comment]
This is likely fixable with @purplesky2016 's new birthdate selector code. That should be ready soon

**Comment by nonprofittechy** [comment]
See: #590
