### ISSUE TITLE
Court selector: don't show the "description" field on the responding court selector

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#684]
The description is not as helpful for a respondent to a case. It could still help a plaintiff choose the court.

Keep in the address field part, because it could help a respondent verify they chose the same court that the form they are looking at is using.

**Comment by BryceStevenWilley** [comment]
I don't think this is relevant anymore, the descriptions as they are now are pretty useful for both the respondent and the plaintiff.

![Screenshot from 2021-05-03 14-40-09](https://user-images.githubusercontent.com/6252212/116918176-917f4c00-ac1d-11eb-905a-c0bbd9ddbba6.png)
