### ISSUE TITLE
209A: Defendant Information - "List everyone who is on the 'other side'"

### ISSUE THREAD

**Issue by LGG233** [SuffolkLITLab/docassemble-MAVirtualCourt#69]
This question is awkward: 
- It's not clear from the question that this is in fact asking for the name of Defendant. Changing the interview question to "Please list everyone who is on the 'other side' of your case below, beginning with Defendant" could ensure that the plaintiff knows to provide Defendant's name here.
- 'Person' could be listed before 'Business or organization' in the multiple choice list – seems more likely the 209A will be filed against a person 
- The "delete" button should only appear when there are names to delete (currently it shows up even when now names are listed.)
- The instruction 'Click "Add another" to add more' should appear immediately above the "add another" button, not at the top of the form where it is separated from the button. Also, these instructions should read 'To add another person or business, click "Add another."' [I would have corrected this myself in the YAML but I could not find this question - is it taken from another interview?]

**Comment by nonprofittechy** [comment]
Thanks @LGG233 , good feedback. We're not using in the 209A stitched up form, so closing this for now
