### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by brooksmk** [SuffolkLITLab/docassemble-MAVirtualCourt#7]
Do we need standard practices for how to handle questions where making a series of datatype: yesno fields behave as pseudo-checkboxes won't do, and instead you need to use datatype: radio? I've only encountered one question where I have to do this so far, so we could just manually code the sections of the attachment blocks for these questions.

**Comment by plocket** [comment]
For my 2 cents, for now I think we leave radio buttons to coders. Dealing with them in the generating process is a bigger deal than it may seem.

**Comment by brooksmk** [comment]
Agreed with Michelle
