### ISSUE TITLE
Add a way to organize documents so it's easier to mark them as enabled/disabled when an interview assembles multiple documents

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#726]
https://docs.google.com/document/d/1TXwaN01IR9z64x901eT2vjaC5_Z-bvUXfSKMedVTEjc/edit?usp=sharing

**Comment by BryceStevenWilley** [comment]
I'd say [ALDocument](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/al_document.py) is in, and pretty successful!
