### ISSUE TITLE
Rename this package to AssemblyLineMA

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#729]

**Comment by BryceStevenWilley** [comment]
Don't think this issue is relevant anymore: our migration was breaking, so we've made https://github.com/SuffolkLITLab/docassemble-AssemblyLine, https://github.com/SuffolkLITLab/docassemble-ALMassachusetts, and https://github.com/SuffolkLITLab/docassemble-MassAccess to take it's place.
