### ISSUE TITLE
Closed: Survey Test 2

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#73]
# Survey result on row 2

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | 1. step 1; 2. step 2; 3. step 3
Expected | A different thing!
Actual | A thing I didn't want!
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1yD19Dw0xaXKWSsrccVgZAbwrZcLkUlrk
Notes | 

Error message
```
test error text
```

---

### Thank you!

**Comment by maevemacglinchey** [comment]
Assessed and closed.
