### ISSUE TITLE
Closed: Survey Test 1

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#74]
# Survey result on row 3

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | Could we format this to make the numbers like: 
1. One
2. Two

Does that work?
Expected | Test
Actual | Test
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1245zJYH5bhm7k09DSbGZn5YXdFmKukRb
Notes | 

Error message
```
Test
```

---

### Thank you!

**Comment by maevemacglinchey** [comment]
Assessed and closed.
