### ISSUE TITLE
Add a custom email button

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#741]
The built-in email option is nice, but the UI is a little confusing. Let's just make our own button that opens a new screen to enter an email address.

Disable the built-in method of displaying the download/email links on all existing production forms.

**Comment by plocket** [comment]
Has this been replaced by the ALDocument work to implement same-page email/download buttons or is this something separate?

**Comment by nonprofittechy** [comment]
Same issue.

**Comment by plocket** [comment]
In that case, here's more that's going on there:
https://github.com/SuffolkLITLab/docassemble-ALDocument/issues/2

https://github.com/SuffolkLITLab/docassemble-ALDocument/tree/email_docs
https://github.com/SuffolkLITLab/docassemble-ALDocument/tree/module_download_table
https://github.com/SuffolkLITLab/docassemble-ALDocument/tree/template_download_table

**Comment by BryceStevenWilley** [comment]
This has long been integrated in ALDocument: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/al_document.py
