### ISSUE TITLE
virtual_court_support.py 'filter_letters' may need fixing

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#746]
`except` uses `reval` instead of `retval`. https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/master/docassemble/MAVirtualCourt/virtual_court_support.py#L309

What is this function used for/what would it be used for? Worth revisiting?

**Comment by nonprofittechy** [comment]
It is required by the affidavit disclosing care or custody. Could move into that package

**Comment by plocket** [comment]
☝️ @purplesky2016

**Comment by purplesky2016** [comment]
Thanks @plocket. Yes, it belongs to 209a repo, therefore it will be deleted from the AL system. See https://docs.google.com/spreadsheets/d/1zjCR7np5cK8ddz3c3F8whhc2phZDqEHKcw9tlY9HyVI/edit#gid=0
