### ISSUE TITLE
Tester feedback: language

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MAVirtualCourt#753]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `summary of fees`
language | on `id: summary of fees` it says "On the next screens, you will provide your name, address, and signature." but only the signature screen follows. I think "screens" is also confusing to the user.
Other information | 
Variable being sought | `fees_interstitial`
Package version | `playground`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Tester contact info | miabonardi

**Comment by BryceStevenWilley** [comment]
I think this refers to https://github.com/SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC/blob/579b620628372987faa2e5978f72b510adbf9d79/docassemble/AffidavitofIndigencyMAVC/data/questions/affidavit_body.yml#L497, right @miabonardi? I'm gonna move this issue to that repo.

**Comment by miabonardi** [comment]
> I think this refers to https://github.com/SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC/blob/579b620628372987faa2e5978f72b510adbf9d79/docassemble/AffidavitofIndigencyMAVC/data/questions/affidavit_body.yml#L497, right @miabonardi? I'm gonna move this issue to that repo.

Correct!
