### ISSUE TITLE
choose a court question title text to allow plaintiff to modify existing order

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#754]
A plaintiff can also be modifying an existing order, so maybe we shouldn't use their status as plaintiff to determine whether to ask them 'What court do you want to file in?' as opposed to 'What court is your case in?'

**Comment by nonprofittechy** [comment]
I have already created some new variables for this in the new AssemblyLine repository (will actually go in the ALMassachusetts.yml for now, but we should circle back and add a more generic court listing)

al_form_type can be one of "starts_case","existing_case","appeal","letter","other" for now. not fully refined.

```
---
if: |
  # this should only be reached if the user's address is out of state
  not len(all_matches)
sets:
  - trial_court
id: choose a court (no matching courts found)
question: |
  % if al_form_type == 'starts_case':
  What court do you want to file in?
  % elif al_form_type == 'appeal':
  What is the name of the trial court your case was originally filed in?
  % else:
  What court is your case in?
  % endif
  ```

**Comment by nonprofittechy** [comment]
Also see #685
