### ISSUE TITLE
Resolved: 209A: Expecting signature page but received error page, row 28

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#99]
# Survey result on row 28

**Report type:** 

---

### Bug

Question | Answer
---|---
Question | 
Actions | I was just finishing up the interview
Expected | Signature page
Actual | Error page 
Feedback | 

---

### Confusion

Question | Answer
---|---
Question | 
Confusion | 
Feedback | 

---

### Something else

_Not sure which one of these spreasheet inputs will get the data_

Question | Answer
---|---
Feedback 1 | 
Feedback 2 | 

---

### Test report

Question | Answer
---|---
Test id | 
Tester | 
Input | 
Expected | 
Actual | 
Link | [Link to specific interview]()
Pic | https://drive.google.com/open?id=1GOq-NakgBd7Vr8Tkvz3uo_rK4OTwWA_k
Notes | 

Error message
```
See attached PDF
```

---

### Thank you!

**Comment by nonprofittechy** [comment]
4/17 version of form
